# Generated by Django 4.2.6 on 2024-06-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioFile',
        ),
    ]
