# Generated by Django 4.2.6 on 2024-07-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_delete_audiofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='summarized_pdf',
            field=models.FileField(blank=True, null=True, upload_to='summarized_pdfs/'),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
