# Generated by Django 4.2.6 on 2024-07-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_pdffile_summarized_pdf_pdffile_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='original_language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
