# Generated by Django 4.2.6 on 2024-06-30 17:56

from django.db import migrations

def add_initial_voices(apps, schema_editor):
    Voice = apps.get_model('audio', 'Voice')
    voices = [
        # English voices
        {'name': 'English Male 1', 'language': 'en', 'gender': 'male'},
        {'name': 'English Male 2', 'language': 'en', 'gender': 'male'},
        {'name': 'English Male 3', 'language': 'en', 'gender': 'male'},
        {'name': 'English Male 4', 'language': 'en', 'gender': 'male'},
        {'name': 'English Male 5', 'language': 'en', 'gender': 'male'},
        {'name': 'English Female 1', 'language': 'en', 'gender': 'female'},
        {'name': 'English Female 2', 'language': 'en', 'gender': 'female'},
        {'name': 'English Female 3', 'language': 'en', 'gender': 'female'},
        {'name': 'English Female 4', 'language': 'en', 'gender': 'female'},
        {'name': 'English Female 5', 'language': 'en', 'gender': 'female'},
        # Tamil voices
        {'name': 'Tamil Male 1', 'language': 'ta', 'gender': 'male'},
        {'name': 'Tamil Male 2', 'language': 'ta', 'gender': 'male'},
        {'name': 'Tamil Male 3', 'language': 'ta', 'gender': 'male'},
        {'name': 'Tamil Male 4', 'language': 'ta', 'gender': 'male'},
        {'name': 'Tamil Male 5', 'language': 'ta', 'gender': 'male'},
        {'name': 'Tamil Female 1', 'language': 'ta', 'gender': 'female'},
        {'name': 'Tamil Female 2', 'language': 'ta', 'gender': 'female'},
        {'name': 'Tamil Female 3', 'language': 'ta', 'gender': 'female'},
        {'name': 'Tamil Female 4', 'language': 'ta', 'gender': 'female'},
        {'name': 'Tamil Female 5', 'language': 'ta', 'gender': 'female'},
        # Malay voices
        {'name': 'Malay Male 1', 'language': 'ms', 'gender': 'male'},
        {'name': 'Malay Male 2', 'language': 'ms', 'gender': 'male'},
        {'name': 'Malay Male 3', 'language': 'ms', 'gender': 'male'},
        {'name': 'Malay Male 4', 'language': 'ms', 'gender': 'male'},
        {'name': 'Malay Male 5', 'language': 'ms', 'gender': 'male'},
        {'name': 'Malay Female 1', 'language': 'ms', 'gender': 'female'},
        {'name': 'Malay Female 2', 'language': 'ms', 'gender': 'female'},
        {'name': 'Malay Female 3', 'language': 'ms', 'gender': 'female'},
        {'name': 'Malay Female 4', 'language': 'ms', 'gender': 'female'},
        {'name': 'Malay Female 5', 'language': 'ms', 'gender': 'female'},
        # Arabic voices
        {'name': 'Arabic Male 1', 'language': 'ar', 'gender': 'male'},
        {'name': 'Arabic Male 2', 'language': 'ar', 'gender': 'male'},
        {'name': 'Arabic Male 3', 'language': 'ar', 'gender': 'male'},
        {'name': 'Arabic Male 4', 'language': 'ar', 'gender': 'male'},
        {'name': 'Arabic Male 5', 'language': 'ar', 'gender': 'male'},
        {'name': 'Arabic Female 1', 'language': 'ar', 'gender': 'female'},
        {'name': 'Arabic Female 2', 'language': 'ar', 'gender': 'female'},
        {'name': 'Arabic Female 3', 'language': 'ar', 'gender': 'female'},
        {'name': 'Arabic Female 4', 'language': 'ar', 'gender': 'female'},
        {'name': 'Arabic Female 5', 'language': 'ar', 'gender': 'female'},
        # Spanish voices
        {'name': 'Spanish Male 1', 'language': 'es', 'gender': 'male'},
        {'name': 'Spanish Male 2', 'language': 'es', 'gender': 'male'},
        {'name': 'Spanish Male 3', 'language': 'es', 'gender': 'male'},
        {'name': 'Spanish Male 4', 'language': 'es', 'gender': 'male'},
        {'name': 'Spanish Male 5', 'language': 'es', 'gender': 'male'},
        {'name': 'Spanish Female 1', 'language': 'es', 'gender': 'female'},
        {'name': 'Spanish Female 2', 'language': 'es', 'gender': 'female'},
        {'name': 'Spanish Female 3', 'language': 'es', 'gender': 'female'},
        {'name': 'Spanish Female 4', 'language': 'es', 'gender': 'female'},
        {'name': 'Spanish Female 5', 'language': 'es', 'gender': 'female'},
    ]
    for voice in voices:
        Voice.objects.create(**voice)

class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_voices),
    ]
