# Generated by Django 4.2.6 on 2024-06-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_add_initial_voices'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='accent',
            field=models.CharField(choices=[('us', 'US'), ('uk', 'UK'), ('au', 'Australian'), ('in', 'Indian')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voice',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('ms', 'Malay'), ('ar', 'Arabic'), ('es', 'Spanish')], max_length=5),
        ),
    ]
