# Generated by Django 4.2.6 on 2024-06-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_voice_accent_alter_voice_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='accent',
            field=models.CharField(choices=[('com', 'US'), ('co.uk', 'UK'), ('com.au', 'Australian'), ('co.in', 'Indian')], max_length=10),
        ),
    ]
