# Generated by Django 4.2.6 on 2024-06-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_alter_voice_accent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice',
            name='accent',
        ),
    ]
