# Generated by Django 4.2.6 on 2024-06-30 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='original_pdfs/')),
                ('original_language', models.CharField(max_length=50)),
                ('translated_file_ms', models.FileField(blank=True, null=True, upload_to='translated_pdfs/')),
                ('translated_file_ta', models.FileField(blank=True, null=True, upload_to='translated_pdfs/')),
                ('translated_file_en', models.FileField(blank=True, null=True, upload_to='translated_pdfs/')),
                ('translated_file_ar', models.FileField(blank=True, null=True, upload_to='translated_pdfs/')),
                ('translated_file_es', models.FileField(blank=True, null=True, upload_to='translated_pdfs/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
