# Generated by Django 4.2.6 on 2024-06-30 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='original_file',
        ),
        migrations.RemoveField(
            model_name='pdfdocument',
            name='original_language',
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='pdf_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='converter.pdffile'),
            preserve_default=False,
        ),
    ]
